apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod-teleport

helmCharts:
  - repo: https://charts.releases.teleport.dev
    name: teleport-cluster
    releaseName: teleport-cluster
    version: 18.1.0
    valuesFile: values.yaml
    namespace: prod-teleport

resources:
  - base/namespace.yaml
  - base/servers-transport.yaml
