apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: argocd-oidc-secret
  namespace: argocd
spec:
  destination:
    create: true
    name: argocd-oidc-secret
    labels: { app.kubernetes.io/part-of: argocd }
  mount: kubesecrets
  path: argocd/argocd-oidc-secret
  type: kv-v2
  vaultAuthRef: prod/vault-auth
