apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: longhorn-system

helmCharts:
  - repo: https://charts.longhorn.io
    name: longhorn
    releaseName: longhorn
    version: 1.8.1
    valuesFile: values.yaml

resources:
  - base/ingress.yaml
  - base/middleware-basic-auth.yaml
  - base/namespace.yaml
