apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: keycloak-db
spec:
  instances: 2
  imageName: ghcr.io/cloudnative-pg/postgresql:17.4

  monitoring:
    enablePodMonitor: true

  bootstrap:
    initdb:
      database: keycloak
      owner: keycloak
      secret:
        name: keycloak-user
  # bootstrap:
  #   pg_basebackup:
  #     source: keycloak-keycloak
  #     database: keycloak
  #     owner: keycloak
  #     secret:
  #       name: keycloak-user
  #
  # externalClusters:
  #   - name: keycloak-keycloak
  #     connectionParameters:
  #       host: keycloak-rw.postgres.svc.cluster.local
  #       user: streaming_replica
  #       sslmode: verify-full
  #     sslKey:
  #       name: ext-keycloak-replication
  #       key: tls.key
  #     sslCert:
  #       name: ext-keycloak-replication
  #       key: tls.crt
  #     sslRootCert:
  #       name: ext-keycloak-ca
  #       key: ca.crt

  storage:
    size: 5Gi
