apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: keycloak
spec:
  instances: 3
  db:
    vendor: postgres
    host: keycloak-db-rw.keycloak.svc.cluster.local
    usernameSecret:
      name: db-credentials
      key: username
    passwordSecret:
      name: db-credentials
      key: password
  http:
    httpEnabled: true
  hostname:
    hostname: keycloak.services.sbling.net
  proxy:
    headers: xforwarded
  ingress:
    enabled: false
