apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: keycloak
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`keycloak.services.sbling.net`)
      kind: Rule
      services:
        - name: keycloak-service
          port: 8080
  tls:
    secretName: keycloak-services-sbling-net-prod-cert
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: keycloak-cert
spec:
  commonName: keycloak.services.sbling.net
  secretName: keycloak-services-sbling-net-prod-cert
  dnsNames:
    - keycloak.services.sbling.net
  issuerRef:
    kind: ClusterIssuer
    name: cert-issuer-prod
