apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: mariadb
spec:
  entryPoints:
    - mariadb
  routes:
    - match: HostSNI(`*`)
      priority: 10
      services:
        - name: mariadb
          port: 3306
  tls:
    secretName: mariadb-services-sbling-net-prod-cert
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mariadb-cert
spec:
  commonName: mariadb.services.sbling.net
  secretName: mariadb-services-sbling-net-prod-cert
  dnsNames:
    - mariadb.services.sbling.net
  issuerRef:
    kind: ClusterIssuer
    name: cert-issuer-prod
