configuration:
  prometheusUrl: http://kube-prometheus-stack-prometheus.platform-monitoring-prometheus.svc.cluster.local:9090
  alertFilterRegexp: ^(Watchdog|InfoInhibitor|RebootRequired|ArgoApplicationUnstable)$
  alertFiringOnly: true

  timeZone: Europe/Rome
  startTime: 1:00
  endTime: 7:00

extraEnvVars:
  - name: KURED_NOTIFY_URL
    valueFrom:
      secretKeyRef:
        name: inchident-bot-secret
        key: url

metrics:
  create: true
