apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vcluster-users
spec:
  destination:
    create: true
    name: vcluster-users
  mount: kubesecrets
  path: vitess/authentication
  type: kv-v2
  vaultAuthRef: prod/vault-auth
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vcluster-mysqld-init
spec:
  destination:
    create: true
    name: vcluster-mysqld-init
  mount: kubesecrets
  path: vitess/init-db
  type: kv-v2
  vaultAuthRef: prod/vault-auth
