apiVersion: planetscale.com/v2
kind: VitessCluster
metadata:
  name: vcluster-prod
spec:
  images:
    vtadmin: vitess/vtadmin:latest
  vtadmin:
    apiAddresses:
      - https://vtadmin.services.sbling.net
    replicas: 1
    readOnly: true
  cells:
    - name: sblingdc
      gateway:
        authentication:
          static:
            secret:
              name: vcluster-users
              key: users.json
        secureTransport:
          tls:
            certSecret:
              name: mysql-services-sbling-net-prod-cert
              key: tls.crt
            keySecret:
              name: mysql-services-sbling-net-prod-cert
              key: tls.key
  keyspaces:
    - name: keycloak
      partitionings:
        - equal:
            parts: 1
            shardTemplate:
              databaseInitScriptSecret:
                name: vcluster-mysqld-init
                key: init_db.sql
              tabletPools:
                - cell: sblingdc
                  type: replica
                  replicas: 3
                  extraVolumes:
                    - name: acl-auth-vol
                      configMap:
                        name: keycloak-acl
                  extraVolumeMounts:
                    - name: acl-auth-vol
                      mountPath: /mnt
                  vttablet:
                    resources:
                      requests:
                        cpu: 100m
                        memory: 256Mi
                    extraFlags:
                      db_charset: utf8mb4
                      enforce-tableacl-config: "true"
                      queryserver-config-strict-table-acl: "true"
                      table-acl-config: /mnt/authorization.json
                      table-acl-config-reload-interval: 5m
                  mysqld:
                    resources:
                      requests:
                        cpu: 100m
                        memory: 256Mi
                  dataVolumeClaimTemplate:
                    accessModes: ["ReadWriteOnce"]
                    resources:
                      requests:
                        storage: 5Gi
  updateStrategy:
    type: Immediate
