apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: homepage
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`homepage.services.sbling.net`)
      kind: Rule
      services:
        - kind: Service
          name: homepage
          port: 3000
          sticky:
            cookie:
              httpOnly: true
              secure: true
              sameSite: none
  tls:
    secretName: homepage-services-sbling-net-prod-cert
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: homepage-cert
spec:
  commonName: homepage.services.sbling.net
  secretName: homepage-services-sbling-net-prod-cert
  dnsNames:
    - homepage.services.sbling.net
  issuerRef:
    kind: ClusterIssuer
    name: cert-issuer-prod
