apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: external-gateway
spec:
  gatewayClassName: cilium
  addresses:
    - type: IPAddress
      value: 172.31.50.129
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      hostname: "*.sbling.net"
    - name: https
      protocol: HTTPS
      port: 443
      hostname: "*.sbling.net"
      allowedRoutes:
        namespaces:
          from: All
      tls:
        certificateRefs:
          - kind: Secret
            name: sbling-net-prod-cert-ext
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: tls-redirect
spec:
  parentRefs:
    - name: external-gateway
      sectionName: http
  rules:
    - filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https
            port: 443
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: sbling-net-prod-cert-ext
spec:
  commonName: "*.sbling.net"
  secretName: sbling-net-prod-cert-ext
  dnsNames:
    - "*.sbling.net"
  issuerRef:
    kind: ClusterIssuer
    name: cert-issuer-prod
