apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: longhorn
  annotations:
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: Longhorn
    gethomepage.dev/description: Cloud native distributed block storage for Kubernetes
    gethomepage.dev/group: Cluster
    gethomepage.dev/icon: longhorn
    gethomepage.dev/pod-selector: ""
    # NOTE: because this is an IngressRoute
    gethomepage.dev/href: https://longhorn.services.sbling.net
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`longhorn.services.sbling.net`)
      kind: Rule
      middlewares:
        - name: oidc-middleware
          namespace: longhorn-system
      services:
        - name: longhorn-frontend
          port: 80
  tls:
    secretName: longhorn-services-sbling-net-prod-cert
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: longhorn-cert
spec:
  commonName: longhorn.services.sbling.net
  secretName: longhorn-services-sbling-net-prod-cert
  dnsNames:
    - longhorn.services.sbling.net
  issuerRef:
    kind: ClusterIssuer
    name: cert-issuer-prod
