apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: longhorn
  annotations:
    # traefik.ingress.kubernetes.io/router.middlewares: longhorn-system-oidc-middleware@kubernetescrd
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: Longhorn
    gethomepage.dev/description: Cloud native distributed block storage for Kubernetes
    gethomepage.dev/group: Cluster
    gethomepage.dev/icon: longhorn
    gethomepage.dev/pod-selector: ""
spec:
  ingressClassName: traefik
  rules:
    - host: longhorn.services.sbling.net
      http:
        paths:
          - backend:
              service:
                name: longhorn-frontend
                port:
                  number: 80
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - longhorn.services.sbling.net
      secretName: longhorn-services-sbling-net-prod-cert
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: longhorn-cert
spec:
  commonName: longhorn.services.sbling.net
  secretName: longhorn-services-sbling-net-prod-cert
  dnsNames:
    - longhorn.services.sbling.net
  issuerRef:
    kind: ClusterIssuer
    name: cert-issuer-prod
