apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: oidc-middleware
spec:
  plugin:
    traefikoidc:
      providerURL: https://dex.services.sbling.net
      clientID: longhorn
      enablePKCE: true
      callbackURL: /oauth2/callback
      logLevel: error
      scopes:
        - openid
        - email
        - profile
        - groups
      allowedRolesAndGroups:
        - Sbling-Technologies:kubernetes-admins
