apiVersion: v1
kind: ConfigMap
metadata:
  name: n8n-config
data:
  N8N_PROXY_HOPS: "1"
  WEBHOOK_URL: https://n8n.sbling.net
  N8N_EDITOR_BASE_URL: https://n8n.services.sbling.net

  # see: https://docs.n8n.io/hosting/configuration/configuration-examples/isolation/
  N8N_DIAGNOSTICS_ENABLED: "false"
  N8N_VERSION_NOTIFICATIONS_ENABLED: "false"
  N8N_TEMPLATES_ENABLED: "false"
  EXTERNAL_FRONTEND_HOOKS_URLS: ""
  N8N_DIAGNOSTICS_CONFIG_FRONTEND: ""
  N8N_DIAGNOSTICS_CONFIG_BACKEND: ""
