apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: n8n-db
spec:
  instances: 2
  imageName: ghcr.io/cloudnative-pg/postgresql:17.4

  monitoring:
    enablePodMonitor: true

  bootstrap:
    initdb:
      database: n8n
      owner: n8n
      secret:
        name: n8n-db-user

  storage:
    storageClass: longhorn-single-replica-retain
    size: 5Gi
