apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: n8n-external-webhooks
spec:
  hostnames:
    - webhooks.sbling.net
  parentRefs:
    - name: external-gateway
      namespace: cilium-system
  rules:
    # TODO: Currently return 500 for matches without webhook data, it would be better if it was 404
    - matches:
        - path:
            type: RegularExpression
            value: ^/n8n/(webhook|webhook-test)/?$

    - backendRefs:
        - name: n8n-webhook
          port: 80
      matches:
        - path:
            type: PathPrefix
            value: /n8n/webhook
      filters:
        - type: URLRewrite
          urlRewrite:
            path:
              type: ReplacePrefixMatch
              replacePrefixMatch: /webhook

    - backendRefs:
        - name: n8n-webhook
          port: 80
      matches:
        - path:
            type: PathPrefix
            value: /n8n/webhook-test
      filters:
        - type: URLRewrite
          urlRewrite:
            path:
              type: ReplacePrefixMatch
              replacePrefixMatch: /webhook-test
---
# NOTE: For some reason if we use the same SVC for both Ingress and HTTPRoute,
# it responds with 503, "no healthy upstream"
apiVersion: v1
kind: Service
metadata:
  name: n8n-webhook
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
  selector:
    app.kubernetes.io/name: n8n
