apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - config-cm.yaml
  - database.yaml
  - deployment.yaml
  - httproute-external.yaml
  - ingress.yaml
  - namespace.yaml
  - network-policy.yaml
  - secrets.yaml
  - volume.yaml
