apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - database.yaml
  - deployment.yaml
  - ingress.yaml
  - namespace.yaml
  - secrets.yaml
  - service.yaml
  - volume.yaml
