apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pelican-panel-db
spec:
  instances: 2
  imageName: ghcr.io/cloudnative-pg/postgresql:17.4

  monitoring:
    enablePodMonitor: true

  bootstrap:
    initdb:
      database: panel
      owner: pelican
      secret:
        name: db-credentials

  storage:
    storageClass: longhorn-single-replica-retain
    size: 5Gi
---
# apiVersion: cilium.io/v2
# kind: CiliumNetworkPolicy
# metadata:
#   name: allow-cnpg-operator
# spec:
#   endpointSelector:
#     matchLabels:
#       cnpg.io/cluster: pelican-panel-db
#   ingress:
#     - fromEndpoints:
#         - matchLabels:
#             io.kubernetes.pod.namespace: cnpg-operator
#   egress:
#     - toEntities:
#         - kube-apiserver
# ---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: db-credentials
spec:
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  data:
    - secretKey: username
      remoteRef:
        key: pelican-panel/db-credentials/username
    - secretKey: password
      remoteRef:
        key: pelican-panel/db-credentials/password
