apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: unpoller
  name: unpoller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: unpoller
  template:
    metadata:
      labels:
        app: unpoller
    spec:
      containers:
        - image: ghcr.io/unpoller/unpoller:v4.0.1@sha256:b2763042859c15301c0db5056de789d75e148b9df25fce97fdb35b854f21edb1
          name: unpoller
          livenessProbe:
            httpGet:
              path: /
              port: tcp
          readinessProbe:
            httpGet:
              path: /
              port: tcp
          ports:
            - containerPort: 9130
              name: tcp
              protocol: TCP
            # - containerPort: 9130
            #   name: udp
            #   protocol: UDP
          volumeMounts:
            - mountPath: /etc/unpoller/up.conf
              name: config-volume
              subPath: up.conf
          envFrom:
            - secretRef:
                name: unifi-credentials
      volumes:
        - name: config-volume
          configMap:
            name: unpoller-config
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: unifi-poller
spec:
  podMetricsEndpoints:
    - port: tcp
  selector:
    matchLabels:
      app: unpoller
