apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: applications
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:Sbling-Technologies/datacenter-k8s.git
    targetRevision: HEAD
    path: apps
  destination:
    name: in-cluster
  syncPolicy:
    automated:
      selfHeal: true
