apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - dashboards.yaml
  - secret.yaml
  - unpoller.yaml

configMapGenerator:
  - name: unpoller-config
    files:
      - up.conf
