apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: unifi-credentials
spec:
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  data:
    - secretKey: UP_UNIFI_CONTROLLER_0_URL
      remoteRef:
        key: monitoring-external/unifi/url
    - secretKey: UP_UNIFI_CONTROLLER_0_USER
      remoteRef:
        key: monitoring-external/unifi/user
    - secretKey: UP_UNIFI_CONTROLLER_0_PASS
      remoteRef:
        key: monitoring-external/unifi/password
