apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: unifi-credentials
spec:
  destination:
    create: true
    name: unifi-credentials
  mount: kubesecrets
  path: monitoring-external/unifi
  type: kv-v2
  vaultAuthRef: prod/vault-auth
