apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: argocd-rules
spec:
  groups:
    - name: ArgoCD Rules
      rules:
        - alert: ArgoApplicationOutOfSync
          annotations:
            summary: "'{{ $labels.name }}' Application has synchronization issues"
            impact: Application is out of sync with the desired state defined in Git repository.
            description: The ArgoCD application '{{ $labels.name }}' is currently out of sync. Please investigate and take necessary actions to synchronize the application.
          expr: argocd_app_info{sync_status="OutOfSync"} == 1
          for: 5m
          labels:
            severity: warning
        - alert: ArgoApplicationUnstable
          annotations:
            summary: "'{{ $labels.name }}' Application is unstable"
            impact: Application is frequently changing state, which may indicate instability or misconfiguration.
            description: The ArgoCD application '{{ $labels.name }}' has been in a 'Progressing' health status while being 'Synced' more than 8 times in the last 24 hours. Please investigate the application's stability and configuration.
          expr: count_over_time(count_over_time(argocd_app_info{health_status="Progressing", sync_status="Synced"}[5m])[24h:5m]) > 8
          for: 0s
          labels:
            severity: warning
