apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: grafana
  labels:
    dashboards: grafana
spec:
  config:
    log:
      mode: console
    date_formats:
      default_timezone: browser
    server:
      root_url: https://grafana.services.sbling.net
    auth:
      disable_login_form: "true"
    auth.generic_oauth:
      enabled: "true"
      name: Keycloak-OAuth
      allow_sign_up: "true"
      client_id: grafana-oauth
      client_secret: ${AUTH_CLIENT_SECRET}
      scopes: openid email profile offline_access roles
      email_attribute_path: email
      login_attribute_path: username
      name_attribute_path: full_name
      groups_attribute_path: groups
      auth_url: https://keycloak.services.sbling.net/realms/sbling/protocol/openid-connect/auth
      token_url: https://keycloak.services.sbling.net/realms/sbling/protocol/openid-connect/token
      api_url: https://keycloak.services.sbling.net/realms/sbling/protocol/openid-connect/userinfo
      signout_redirect_url: https://keycloak.services.sbling.net/realms/sbling/protocol/openid-connect/logout?post_logout_redirect_uri=https%3A%2F%2Fgrafana.services.sbling.net%2Flogin
      role_attribute_path: contains(roles[*], 'admin') && 'Admin' || contains(roles[*], 'editor') && 'Editor' || 'Viewer'

  deployment:
    spec:
      template:
        spec:
          containers:
            - name: grafana
              env:
                - name: AUTH_CLIENT_SECRET
                  valueFrom:
                    secretKeyRef:
                      name: grafana-oidc-secret
                      key: client-secret

  ingress:
    spec:
      ingressClassName: traefik
      rules:
        - host: grafana.services.sbling.net
          http:
            paths:
              - backend:
                  service:
                    name: grafana-service
                    port:
                      number: 3000
                path: /
                pathType: Prefix
      tls:
        - hosts:
            - grafana.services.sbling.net
          secretName: grafana-services-sbling-net-prod-cert
