apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: grafana
  labels:
    dashboards: grafana
spec:
  config:
    log:
      mode: console
      level: debug
    date_formats:
      default_timezone: browser
    server:
      root_url: https://grafana.services.sbling.net
    auth:
      disable_login_form: "true"
    auth.generic_oauth:
      enabled: "true"
      name: Keycloak-OAuth
      allow_sign_up: "true"
      client_id: grafana-oauth
      client_secret: ${AUTH_CLIENT_SECRET}
      scopes: openid email profile offline_access roles
      email_attribute_path: email
      login_attribute_path: username
      name_attribute_path: full_name
      auth_url: https://keycloak.services.sbling.net/realms/sbling/protocol/openid-connect/auth
      token_url: https://keycloak.services.sbling.net/realms/sbling/protocol/openid-connect/token
      api_url: https://keycloak.services.sbling.net/realms/sbling/protocol/openid-connect/userinfo
      role_attribute_path: >-
        contains(roles[*], 'admin') && 'Admin' ||
        contains(roles[*], 'editor') && 'Editor' ||
        'Viewer'

  deployment:
    spec:
      template:
        spec:
          containers:
            - name: grafana
              env:
                - name: AUTH_CLIENT_SECRET
                  valueFrom:
                    secretKeyRef:
                      name: grafana-oidc-secret
                      key: client-secret
          securityContext:
            fsGroup: 10001
          volumes:
            - name: grafana-data
              persistentVolumeClaim:
                claimName: grafana-pvc

  persistentVolumeClaim:
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi

  ingress:
    metadata:
      annotations:
        gethomepage.dev/enabled: "true"
        gethomepage.dev/name: Grafana
        gethomepage.dev/description: Dashboards & graphs
        gethomepage.dev/group: Monitoring
        gethomepage.dev/icon: grafana
        gethomepage.dev/pod-selector: ""
    spec:
      ingressClassName: traefik
      rules:
        - host: grafana.services.sbling.net
          http:
            paths:
              - backend:
                  service:
                    name: grafana-service
                    port:
                      number: 3000
                path: /
                pathType: Prefix
      tls:
        - hosts:
            - grafana.services.sbling.net
          secretName: grafana-services-sbling-net-prod-cert
