apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: grafana
  labels:
    dashboards: grafana
spec:
  config:
    log:
      mode: console
    auth:
      disable_login_form: "false"
    date_formats:
      default_timezone: browser
  ingress:
    spec:
      ingressClassName: traefik
      rules:
        - host: grafana.services.sbling.net
          http:
            paths:
              - backend:
                  service:
                    name: grafana-service
                    port:
                      number: 3000
                path: /
                pathType: Prefix
      tls:
        - hosts:
            - grafana.services.sbling.net
          secretName: grafana-services-sbling-net-prod-cert
