apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: grafana-oidc-secret
spec:
  destination:
    create: true
    name: grafana-oidc-secret
  mount: kubesecrets
  path: monitoring-system/grafana-oidc-secret
  type: kv-v2
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: inchident-bot-secret
spec:
  destination:
    create: true
    name: inchident-bot-secret
  mount: kubesecrets
  path: shared/inchident-bot
  type: kv-v2
