apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kibana

resources:
  - base/deployment.yaml
  - base/ingress.yaml
  - base/kibana-es-credentials.yaml
  - base/namespace.yaml
