apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: portainer
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`portainer.services.sbling.net`)
      kind: Rule
      services:
        - name: portainer
          port: 9443
          serversTransport: no-verify-tls
  tls:
    secretName: portainer-services-sbling-net-prod-cert
---
apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: no-verify-tls
spec:
  insecureSkipVerify: true
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: portainer-cert
spec:
  commonName: portainer.services.sbling.net
  secretName: portainer-services-sbling-net-prod-cert
  dnsNames:
    - portainer.services.sbling.net
  issuerRef:
    kind: ClusterIssuer
    name: cert-issuer-prod
