apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: inchident-bot-secret
spec:
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    template:
      data:
        url: "telegram://{{ .token }}@telegram?chats={{ .chat_id }}"
  data:
    - secretKey: token
      remoteRef:
        key: shared/inchident-bot/token
    - secretKey: chat_id
      remoteRef:
        key: shared/inchident-bot/chat_id
