apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: carpoolerbot-db
spec:
  instances: 2
  imageName: ghcr.io/cloudnative-pg/postgresql:17.4

  monitoring:
    enablePodMonitor: true

  bootstrap:
    initdb:
      database: carpoolerbot
      owner: carpoolerbot
      secret:
        name: carpoolerbot-db-user

  storage:
    size: 5Gi
