apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - pairs:
      app: carpoolerbot
    includeSelectors: true

resources:
  - database.yaml
  - deployment.yaml
  - grafana-datasource.yaml
  - secrets.yaml
