apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: carpoolerbot-env
spec:
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  data:
    - secretKey: TELEGRAM_TOKEN
      remoteRef:
        key: telegram-bots/carpoolerbot/telegram-token
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: carpoolerbot-db-user
spec:
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  data:
    - secretKey: username
      remoteRef:
        key: telegram-bots/carpoolerbot/db-credentials/username
    - secretKey: password
      remoteRef:
        key: telegram-bots/carpoolerbot/db-credentials/password
