apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - repo: https://charts.bitnami.com/bitnami
    name: kafka
    releaseName: kafka
    version: 32.4.3
    valuesFile: values.yaml
    namespace: prod-unitn-tg-bot
