apiVersion: k8s.mariadb.com/v1alpha1
kind: Database
metadata:
  name: keycloak
spec:
  mariaDbRef:
    name: mariadb
    namespace: mariadb
  characterSet: utf8
  collate: utf8_general_ci
  cleanupPolicy: Skip
  requeueInterval: 30s
  retryInterval: 5s
---
apiVersion: k8s.mariadb.com/v1alpha1
kind: User
metadata:
  name: keycloak
spec:
  mariaDbRef:
    name: mariadb
    namespace: mariadb
  passwordSecretKeyRef:
    name: db-credentials
    key: password
  host: "%"
  cleanupPolicy: Delete
  requeueInterval: 30s
  retryInterval: 5s
---
apiVersion: k8s.mariadb.com/v1alpha1
kind: Grant
metadata:
  name: db-user-grant
spec:
  mariaDbRef:
    name: mariadb
    namespace: mariadb
  privileges:
    - "ALL"
  database: keycloak
  table: "*"
  username: keycloak
  grantOption: false
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: db-credentials
spec:
  destination:
    create: true
    name: db-credentials
  mount: kubesecrets
  path: keycloak/db-credentials
  type: kv-v2
  vaultAuthRef: prod/vault-auth
