apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: db-credentials
spec:
  destination:
    create: true
    name: db-credentials
  mount: kubesecrets
  path: keycloak/db-credentials
  type: kv-v2
  vaultAuthRef: prod/vault-auth
