apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: vitess

resources:
  - base/mysql-ingress.yaml
  - base/namespace.yaml
  - base/secrets.yaml
  - base/vcluster-prod.yaml
  - base/vtadmin-ingress.yaml
  - https://raw.githubusercontent.com/vitessio/vitess/refs/heads/main/examples/operator/operator.yaml

configMapGenerator:
  - name: keycloak-acl
    files:
      - authorization.json=acls/keycloak.json
    options:
      disableNameSuffixHash: true

images:
  - name: planetscale/vitess-operator
    newTag: v2.14.0
