apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-redis-ha-haproxy
spec:
  strategy:
    rollingUpdate:
      # due to rolling update in combination with anti affinity rules and nodes count=replica count
      maxUnavailable: 34%
  template:
    spec:
      automountServiceAccountToken: true # TODO: Remove this once fixed upstream https://github.com/argoproj/argo-cd/issues/22226
