- op: add
  path: /spec/ingress/-
  value:
    from:
      - namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: platform-monitoring-prometheus
    ports:
      - port: 9101
        protocol: TCP
