apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: metallb-system

helmCharts:
  - repo: https://metallb.github.io/metallb
    name: metallb
    releaseName: metallb
    version: 0.15.2
    namespace: metallb-system

resources:
  - base/ipaddrpool.yaml
  - base/l2advertisement.yaml
