apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: renso-ghcrio
spec:
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: |-
          {
            "auths": {
              "{{ .registry }}": {
                "auth": "{{ printf "%s:%s" .username .password | b64enc }}"
              }
            }
          }
  data:
    - secretKey: registry
      remoteRef:
        key: docker-registry/renso-ghcrio/registry
    - secretKey: username
      remoteRef:
        key: docker-registry/renso-ghcrio/username
    - secretKey: password
      remoteRef:
        key: docker-registry/renso-ghcrio/password
