apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod-kestra

helmCharts:
  - repo: https://helm.kestra.io
    name: kestra
    releaseName: kestra
    version: 0.23.1
    valuesFile: values.yaml
    namespace: prod-kestra

resources:
  - base/certificate.yaml
  - base/namespace.yaml
