dind:
  enabled: false

ingress:
  enabled: true
  annotations:
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: Kestra
    gethomepage.dev/description: Workflow Automation Platform.
    gethomepage.dev/group: Services
    gethomepage.dev/icon: kestra
    gethomepage.dev/pod-selector: ""

  className: traefik
  hosts:
    - host: kestra.services.sbling.net
      paths:
        - pathType: Prefix
          path: /
  tls:
    - secretName: kestra-services-sbling-net-prod-cert
      hosts:
        - kestra.services.sbling.net
