apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: wallabag-db
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:17.4

  bootstrap:
    initdb:
      database: wallabag
      owner: wallabag
      secret:
        name: wallabag-db-user

  storage:
    size: 5Gi
