apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: wallabag-db-user
spec:
  destination:
    create: true
    name: wallabag-db-user
  mount: kubesecrets
  path: wallabag/db-credentials
  type: kv-v2
