apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: harbor-db
spec:
  instances: 3
  imageName: ghcr.io/cloudnative-pg/postgresql:17.4
  bootstrap:
    initdb:
      database: harbor
      owner: harbor
      secret:
        name: db-credentials
  storage:
    size: 5Gi
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-cnpg-operator
spec:
  endpointSelector:
    matchLabels:
      cnpg.io/cluster: harbor-db
  ingress:
    - fromEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: cnpg-operator
  egress:
    - toEntities:
        - kube-apiserver
