apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: harbor-db
spec:
  instances: 3
  imageName: ghcr.io/cloudnative-pg/postgresql:17.4
  bootstrap:
    initdb:
      database: harbor
      owner: harbor
      secret:
        name: db-credentials
  storage:
    size: 5Gi
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-cnpg-operator
spec:
  podSelector:
    matchLabels:
      cnpg.io/cluster: harbor-db
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: cnpg-operator
  egress:
    - to:
        - ipBlock:
            # IP of the "kubernetes" service in the "default" namespace
            cidr: 10.43.0.1/32
      ports:
        - protocol: TCP
          port: 443
