apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: default-deny-cross-namespace
spec:
  description: >-
    Deny all cross-namespace traffic.
    Allow all intra-namespace traffic.
    Allow outbound traffic to kube-dns.
  endpointSelector: {}
  ingress:
    - fromEndpoints:
        - {}
  egress:
    - toEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: kube-system
            k8s-app: kube-dns
      toPorts:
        - ports:
            - port: "53"
              protocol: UDP
          rules:
            dns:
              - matchPattern: "*"
    - toEndpoints:
        - {}
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-from-ingress
spec:
  description: Allow inbound traffic from ingress controller
  endpointSelector: {}
  ingress:
    - fromEntities:
        - ingress
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-to-dex
spec:
  endpointSelector: {}
  egress:
    # NOTE: Cilium does some optimizations so this is the only way this works
    - toEndpoints:
        - matchLabels:
            k8s:app.kubernetes.io/name: dex
            k8s:io.kubernetes.pod.namespace: dex
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-monitoring
spec:
  description: Allow inbound traffic from monitoring system (Prometheus)
  endpointSelector: {}
  ingress:
    - fromEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: platform-monitoring-prometheus
            app.kubernetes.io/name: prometheus
