apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: db-credentials
spec:
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  data:
    - secretKey: username
      remoteRef:
        key: harbor/db-credentials/username
    - secretKey: password
      remoteRef:
        key: harbor/db-credentials/password
