apiVersion: apps/v1
kind: Deployment
metadata:
  name: homepage
spec:
  revisionHistoryLimit: 3
  replicas: 2
  strategy:
    type: RollingUpdate
  template:
    spec:
      serviceAccountName: homepage
      automountServiceAccountToken: true
      dnsPolicy: ClusterFirst
      enableServiceLinks: true
      containers:
        - name: homepage
          image: ghcr.io/gethomepage/homepage:v1.13.0@sha256:690ac1f79e33000c176c2a28229ed00b49b44781e8a63f280a8ece22c161f099
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          volumeMounts:
            - mountPath: /app/config
              name: homepage-config
            - mountPath: /app/public/icons
              name: homepage-icons
            - mountPath: /app/config/logs
              name: logs
          envFrom:
            - secretRef:
                name: homepage-env
          env:
            - name: HOMEPAGE_ALLOWED_HOSTS
              value: homepage.services.sbling.net
      volumes:
        - name: homepage-config
          configMap:
            name: homepage-config
        - name: homepage-icons
          configMap:
            name: homepage-icons
        - name: logs
          emptyDir: {}
