apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: homepage
spec:
  ingressClassName: traefik
  rules:
    - host: homepage.services.sbling.net
      http:
        paths:
          - backend:
              service:
                name: homepage
                port:
                  number: 3000
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - homepage.services.sbling.net
      secretName: homepage-services-sbling-net-prod-cert
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: homepage-cert
spec:
  commonName: homepage.services.sbling.net
  secretName: homepage-services-sbling-net-prod-cert
  dnsNames:
    - homepage.services.sbling.net
  issuerRef:
    kind: ClusterIssuer
    name: cert-issuer-prod
