apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: homepage-env
spec:
  destination:
    create: true
    name: homepage-env
  mount: kubesecrets
  path: homepage/env
  type: kv-v2
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: oidc-secret
spec:
  destination:
    create: true
    name: oidc-secret
  mount: kubesecrets
  path: homepage/oidc-secret
  type: kv-v2
