apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: homepage-env
spec:
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  data:
    - secretKey: HOMEPAGE_VAR_PROXMOX_USER
      remoteRef:
        key: homepage/env/proxmox-user
    - secretKey: HOMEPAGE_VAR_PROXMOX_PSWD
      remoteRef:
        key: homepage/env/proxmox-pswd

    - secretKey: HOMEPAGE_VAR_TRUENAS_KEY
      remoteRef:
        key: homepage/env/truenas-key

    - secretKey: HOMEPAGE_VAR_UNIFI_USER
      remoteRef:
        key: homepage/env/unifi-user
    - secretKey: HOMEPAGE_VAR_UNIFI_PSWD
      remoteRef:
        key: homepage/env/unifi-pswd
