apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: keycloak

helmCharts:
  - repo: oci://registry-1.docker.io/bitnamicharts
    name: keycloak
    releaseName: keycloak
    version: 24.4.9
    valuesFile: values.yaml

resources:
  - base/database.yaml
  - base/ingress.yaml
  - base/namespace.yaml

images:
  - name: docker.io/bitnami/keycloak
    newTag: 26.1.1-debian-12-r0
