# NOTE: Images are automatically updated when the chart version is updated

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: keycloak

helmCharts:
  - repo: oci://registry-1.docker.io/bitnamicharts
    name: keycloak
    releaseName: keycloak
    version: 24.4.11
    valuesFile: values.yaml

resources:
  - base/ingress.yaml
  - base/namespace.yaml
  - base/secrets.yaml

patches:
  - target:
      group: apps
      version: v1
      kind: StatefulSet
      name: keycloak
    path: ./overlays/statefulset-patch.yaml
