apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    io.kompose.service: maps-svc
  name: maps-svc
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: maps-svc
  serviceName: maps-svc
  template:
    metadata:
      labels:
        io.kompose.service: maps-svc
    spec:
      containers:
        - image: ghcr.io/guss-alberto/unitntgbot-maps:v0.1.0
          name: maps-svc
          ports:
            - containerPort: 5000
              protocol: TCP
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: maps-svc
  name: maps-svc
spec:
  clusterIP: None
  ports:
    - name: http
      port: 80
      targetPort: 5000
  selector:
    io.kompose.service: maps-svc
