apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: elasticsearch
spec:
  entryPoints:
    - elasticsearch
  routes:
    - match: Host(`elasticsearch.services.sbling.net`)
      kind: Rule
      services:
        - name: es-node01-svc
          port: 9200
          scheme: https
          serversTransport: es-root-ca
        - name: es-node02-svc
          port: 9200
          scheme: https
          serversTransport: es-root-ca
        - name: es-node03-svc
          port: 9200
          scheme: https
          serversTransport: es-root-ca
  tls:
    secretName: elasticsearch-services-sbling-net-prod-cert
---
apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: es-root-ca
spec:
  rootCAsSecrets:
    - es-root-ca
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: elastic-load-balanced-cert
spec:
  commonName: elasticsearch.services.sbling.net
  secretName: elasticsearch-services-sbling-net-prod-cert
  dnsNames:
    - elasticsearch.services.sbling.net
  issuerRef:
    kind: ClusterIssuer
    name: cert-issuer-prod
