apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: sbling-regcred
spec:
  destination:
    create: true
    name: sbling-regcred
    type: "kubernetes.io/dockerconfigjson"
  mount: kubesecrets
  path: harbor/sbling-regcred
  type: kv-v2
