globalArguments:
  - "--global.sendanonymoususage=false"

additionalArguments:
  - "--providers.kubernetescrd"
  - "--providers.kubernetesingress.allowemptyservices=true"
  - "--providers.kubernetesingress.allowexternalnameservices=true"
  - "--providers.kubernetescrd.allowemptyservices=true"
  - "--providers.kubernetescrd.allowexternalnameservices=true"

experimental:
  plugins:
    traefikoidc:
      moduleName: github.com/lukaszraczylo/traefikoidc
      version: v0.5.34

deployment:
  replicas: 2

ports:
  web:
    redirections:
      entryPoint:
        to: websecure
        scheme: https
  elasticsearch:
    port: 9200
    exposedPort: 9200
    expose:
      default: true
    protocol: TCP
    tls:
      enabled: true
  fleet-server:
    port: 8220
    exposedPort: 8220
    expose:
      default: true
    protocol: TCP
    tls:
      enabled: true

tlsStore:
  default:
    defaultCertificate:
      secretName: traefik-default-services-sbling-net-prod-cert

service:
  annotations:
    metallb.universe.tf/loadBalancerIPs: 172.31.50.128

ingressRoute:
  dashboard:
    enabled: true
    # matchRule: Host(`traefik-k8s.services.sbling.net`)
    # services:
    #   - name: api@internal
    #     kind: TraefikService
    # middlewares:
    #   - name: oidc-middleware
    #     namespace: traefik-system
    # tls:
    #   secretName: traefik-k8s-services-sbling-net-prod-cert

ingressClass:
  enabled: true
  isDefaultClass: true
  name: traefik
