apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kube-state-metrics

resources:
  - base/namespace.yaml
  - https://raw.githubusercontent.com/kubernetes/kube-state-metrics/refs/heads/main/examples/daemonsetsharding/cluster-role-binding.yaml
  - https://raw.githubusercontent.com/kubernetes/kube-state-metrics/refs/heads/main/examples/daemonsetsharding/cluster-role.yaml
  - https://raw.githubusercontent.com/kubernetes/kube-state-metrics/refs/heads/main/examples/daemonsetsharding/daemonset-service.yaml
  - https://raw.githubusercontent.com/kubernetes/kube-state-metrics/refs/heads/main/examples/daemonsetsharding/daemonset.yaml
  - https://raw.githubusercontent.com/kubernetes/kube-state-metrics/refs/heads/main/examples/daemonsetsharding/deployment-service.yaml
  - https://raw.githubusercontent.com/kubernetes/kube-state-metrics/refs/heads/main/examples/daemonsetsharding/deployment-unscheduled-pods-fetching-service.yaml
  - https://raw.githubusercontent.com/kubernetes/kube-state-metrics/refs/heads/main/examples/daemonsetsharding/deployment-unscheduled-pods-fetching.yaml
  - https://raw.githubusercontent.com/kubernetes/kube-state-metrics/refs/heads/main/examples/daemonsetsharding/deployment.yaml
  - https://raw.githubusercontent.com/kubernetes/kube-state-metrics/refs/heads/main/examples/daemonsetsharding/service-account.yaml
