configSecret:
  create: false
  name: dex-config

envFrom:
  - secretRef:
      name: dex-secrets

ingress:
  enabled: true
  hosts:
    - host: &host dex.services.sbling.net
      paths:
        - path: /
          pathType: Prefix

  tls:
    - hosts:
        - *host

serviceMonitor:
  enabled: true
