cluster:
  name: datacenter-k8s

destinations:
  - name: loki
    type: loki
    url: http://loki-gateway/loki/api/v1/push

clusterEvents:
  enabled: true

nodeLogs:
  enabled: true

podLogs:
  enabled: true
  gatherMethod: kubernetesApi

alloy-singleton:
  enabled: true

alloy-logs:
  enabled: true
  alloy:
    mounts:
      varlog: true
    clustering:
      enabled: true
