apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: bitwarden-ca-issuer
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: bitwarden-ca-cert
spec:
  isCA: true
  secretName: bitwarden-ca-cert
  subject:
    organizations:
      - external-secrets.io
  dnsNames:
    - bitwarden-sdk-server.external-secrets.svc.cluster.local
  issuerRef:
    name: bitwarden-ca-issuer
    kind: Issuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: bitwarden-certificate-issuer
spec:
  ca:
    secretName: bitwarden-ca-cert
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: bitwarden-tls-certs
spec:
  secretName: bitwarden-tls-certs
  dnsNames:
    - bitwarden-sdk-server.external-secrets.svc.cluster.local
  issuerRef:
    name: bitwarden-certificate-issuer
    kind: Issuer
    group: cert-manager.io
