apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: bitwarden-secretsmanager
spec:
  provider:
    bitwardensecretsmanager:
      apiURL: https://vault.bitwarden.eu/api
      identityURL: https://vault.bitwarden.eu/identity
      organizationID: 6b5da240-14b5-41d6-bcd0-b347016da9e1
      projectID: 8586f073-f2ee-41df-b5fa-b347016efea3
      auth:
        secretRef:
          credentials:
            key: token
            name: bitwarden-access-token
            namespace: external-secrets
      bitwardenServerSDKURL: https://bitwarden-sdk-server.external-secrets.svc.cluster.local:9998
      # NOTE: Not the best thing due to the secret also having the private key.
      # https://cert-manager.io/docs/trust/
      caProvider:
        type: Secret
        key: ca.crt
        name: bitwarden-tls-certs
        namespace: external-secrets
