apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: pushsecret-kubechecks
spec:
  secretStoreRefs:
    - name: bitwarden-secretsmanager
      kind: ClusterSecretStore
  selector:
    secret:
      name: kubechecks-apikey
  data:
    - match:
        secretKey: token
        remoteRef:
          remoteKey: kubechecks/argocd/api-key
