apiVersion: apps/v1
kind: Deployment
metadata:
  name: wpdevspranzobot
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: wpdevspranzobot
          image: ghcr.io/luigimiazzo17/wpdevspranzobot:v0.2.0
          env:
            - name: TZ
              value: Europe/Rome
            - name: HOURS
              value: "17"
            - name: MINUTES
              value: "0"
            - name: IT_PROVINCE
              value: "BZ"
            - name: CUSTOM_SKIP_DATES
              value: "24-12,31-12"
          envFrom:
            - secretRef:
                name: wpdevspranzobot-env
