apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: wpdevspranzobot-env
spec:
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  data:
    - secretKey: TELEGRAM_TOKEN
      remoteRef:
        key: telegram-bots/wpdevspranzobot/telegram-token
    - secretKey: CHAT_ID
      remoteRef:
        key: telegram-bots/wpdevspranzobot/chat_id
