apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: elasticsearch
spec:
  entryPoints:
    - elasticsearch
  routes:
    - match: Host(`elasticsearch.services.sbling.net`)
      kind: Rule
      middlewares:
        - name: add-proxy-suffix
      services:
        - name: elastic-proxy
          port: 8080
          scheme: http
  tls:
    secretName: internal-ingress-cert
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: internal-ingress-cert
spec:
  commonName: elasticsearch.services.sbling.net
  secretName: internal-ingress-cert
  dnsNames:
    - elasticsearch.services.sbling.net
  issuerRef:
    kind: ClusterIssuer
    name: cert-issuer-prod
