apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert-prod
  namespace: prod
spec:
  commonName: services.sbling.net
  secretName: services-sbling-net-prod-cert
  dnsNames:
    - "*.services.sbling.net"
    - services.sbling.net
  issuerRef:
    kind: ClusterIssuer
    name: cert-issuer-prod
