apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: vault-auth
  namespace: prod
spec:
  vaultConnectionRef: vault/vault-connection
  method: kubernetes
  mount: kubernetes
  allowedNamespaces:
    - argocd
    - authentik
    - kibana
    - kube-system
    - longhorn-system
    - prod-gatus
    - prod-homepage
    - prod-keycloak
    - prod-telegram-bots
    - traefik-system
  kubernetes:
    role: kubesecret-reader
    serviceAccount: default
