apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: icinga-ticket-salt
spec:
  destination:
    create: true
    name: icinga-ticket-salt
  mount: kubesecrets
  path: icinga/ticket-salt
  type: kv-v2
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: icingaweb-admin-user
spec:
  destination:
    create: true
    name: icingaweb-admin-user
  mount: kubesecrets
  path: icinga/icingaweb-admin-user
  type: kv-v2
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: icinga-api-users
spec:
  destination:
    create: true
    name: icinga-api-users
  mount: kubesecrets
  path: icinga/icinga-api-users
  type: kv-v2
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: icinga-database-users
spec:
  destination:
    create: true
    name: icinga-database-users
  mount: kubesecrets
  path: icinga/icinga-database-users
  type: kv-v2
