apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: icinga-ticket-salt
spec:
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  data:
    - secretKey: ticket-salt
      remoteRef:
        key: icinga/ticket-salt
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: icingaweb-admin-user
spec:
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  data:
    - secretKey: password
      remoteRef:
        key: icinga/icingaweb-admin-password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: icinga-api-users
spec:
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  data:
    - secretKey: director-password
      remoteRef:
        key: icinga/api-users/director-password
    - secretKey: icingaweb-password
      remoteRef:
        key: icinga/api-users/icingaweb-password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: icinga-database-users
spec:
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  data:
    - secretKey: director-password
      remoteRef:
        key: icinga/database-users/director-password
    - secretKey: icingadb-password
      remoteRef:
        key: icinga/database-users/icingadb-password
    - secretKey: icingaweb-password
      remoteRef:
        key: icinga/database-users/icingaweb-password
