apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - repo: https://prometheus-community.github.io/helm-charts
    name: kube-prometheus-stack
    releaseName: kube-prometheus-stack
    includeCRDs: true
    version: 79.0.0
    valuesFile: values.yaml
    namespace: monitoring-system

resources:
  - grafana-datasource.yaml
  - secrets.yaml
