apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: inchident-bot-secret
spec:
  destination:
    create: true
    name: inchident-bot-secret
  mount: kubesecrets
  path: shared/inchident-bot
  type: kv-v2
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: healthcheck-io-webhook
spec:
  destination:
    create: true
    name: healthcheck-io-webhook
  mount: kubesecrets
  path: monitoring-system/healthcheck-io-webhook
  type: kv-v2
