grafana:
  enabled: false
  forceDeployDashboards: true
  operator:
    dashboardsConfigMapRefEnabled: true
    matchLabels:
      dashboards: grafana

kubeControllerManager:
  endpoints:
    - 172.31.50.48
    - 172.31.50.49
    - 172.31.50.50

kubeEtcd:
  endpoints:
    - 172.31.50.48
    - 172.31.50.49
    - 172.31.50.50

kubeScheduler:
  endpoints:
    - 172.31.50.48
    - 172.31.50.49
    - 172.31.50.50

kubeProxy:
  endpoints:
    - 172.31.50.48
    - 172.31.50.49
    - 172.31.50.50
