grafana:
  enabled: false
  forceDeployDashboards: true
  operator:
    dashboardsConfigMapRefEnabled: true
    folder: Kubernetes Default
    matchLabels:
      dashboards: grafana

nodeExporter:
  operatingSystems:
    aix:
      enabled: false
    darwin:
      enabled: false

kubeControllerManager:
  endpoints:
    - 172.31.50.48
    - 172.31.50.49
    - 172.31.50.50

kubeEtcd:
  endpoints:
    - 172.31.50.48
    - 172.31.50.49
    - 172.31.50.50

kubeScheduler:
  endpoints:
    - 172.31.50.48
    - 172.31.50.49
    - 172.31.50.50

kubeProxy:
  endpoints:
    - 172.31.50.48
    - 172.31.50.49
    - 172.31.50.50

prometheus:
  prometheusSpec:
    replicas: 2
    retentionSize: 30GiB
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: longhorn-single-replica
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 30Gi

    ruleSelectorNilUsesHelmValues: false
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    probeSelectorNilUsesHelmValues: false
    scrapeConfigSelectorNilUsesHelmValues: false
