grafana:
  enabled: false
  forceDeployDashboards: true
  operator:
    dashboardsConfigMapRefEnabled: true
    folder: Kubernetes Default
    matchLabels:
      dashboards: grafana

nodeExporter:
  operatingSystems:
    aix:
      enabled: false
    darwin:
      enabled: false

kubeControllerManager:
  endpoints:
    - 172.31.50.48
    - 172.31.50.49
    - 172.31.50.50

kubeEtcd:
  endpoints:
    - 172.31.50.48
    - 172.31.50.49
    - 172.31.50.50

kubeScheduler:
  endpoints:
    - 172.31.50.48
    - 172.31.50.49
    - 172.31.50.50

# NOTE: Replaced by Cilium
kubeProxy:
  enabled: false

prometheus:
  prometheusSpec:
    replicas: 2
    enableFeatures:
      - exemplar-storage
    retentionSize: 40GiB
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: longhorn-single-replica
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 50Gi

    ruleSelectorNilUsesHelmValues: false
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    probeSelectorNilUsesHelmValues: false
    scrapeConfigSelectorNilUsesHelmValues: false

alertmanager:
  alertmanagerSpec:
    secrets:
      - inchident-bot-secret
      - healthcheck-io-webhook

  config:
    route:
      receiver: inchident-telegram-receiver
      routes:
        - receiver: healthcheck-io-webhook
          group_interval: 1m
          repeat_interval: 50s
          group_wait: 0s
          matchers:
            - alertname = "Watchdog"
    receivers:
      - name: inchident-telegram-receiver
        telegram_configs:
          - bot_token_file: /etc/alertmanager/secrets/inchident-bot-secret/token
            chat_id: -1001844822513
      - name: healthcheck-io-webhook
        webhook_configs:
          - url_file: /etc/alertmanager/secrets/healthcheck-io-webhook/url
