commonLabels:
  monitoring: system

grafana:
  enabled: false
  forceDeployDashboards: true
  operator:
    dashboardsConfigMapRefEnabled: true
    matchLabels:
      dashboards: grafana

kubeControllerManager:
  endpoints:
    - 172.31.50.48
    - 172.31.50.49
    - 172.31.50.50

kubeEtcd:
  endpoints:
    - 172.31.50.48
    - 172.31.50.49
    - 172.31.50.50

kubeScheduler:
  endpoints:
    - 172.31.50.48
    - 172.31.50.49
    - 172.31.50.50

kubeProxy:
  endpoints:
    - 172.31.50.48
    - 172.31.50.49
    - 172.31.50.50

prometheus:
  prometheusSpec:
    ruleSelector:
      matchLabels:
        monitoring: system

    serviceMonitorSelector:
      matchLabels:
        monitoring: system

    podMonitorSelector:
      matchLabels:
        monitoring: system

    probeSelector:
      matchLabels:
        monitoring: system

    scrapeConfigSelector:
      matchLabels:
        monitoring: system
