apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: infra-longhorn

helmCharts:
  - repo: https://charts.longhorn.io
    name: longhorn
    releaseName: longhorn
    version: 1.8.1
    valuesFile: values.yaml
    namespace: infra-longhorn

resources:
  - base/ingress.yaml
  - base/middleware-oidc-auth.yaml
  - base/namespace.yaml
  - base/secrets.yaml
