apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: default
  namespace: vault
spec:
  vaultConnectionRef: vault-connection
  method: kubernetes
  mount: kubernetes
  allowedNamespaces:
    - argocd
    - kube-system
    - longhorn-system
    - monitoring-external
    - monitoring-system
    - prod-gatus
    - prod-harbor
    - prod-homepage
    - prod-keycloak
    - prod-kibana
    - prod-telegram-bots
    - prod-wallabag
    - prod-unitn-tg-bot
    - traefik-system
  kubernetes:
    role: kubesecret-reader
    serviceAccount: default
