apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: vault-auth
  namespace: vault
spec:
  vaultConnectionRef: vault/vault-connection
  method: kubernetes
  mount: kubernetes
  allowedNamespaces:
    - argocd
    - kube-system
    - longhorn-system
    - monitoring-external
    - prod-elasticsearch
    - prod-gatus
    - prod-harbor
    - prod-homepage
    - prod-keycloak
    - prod-kibana
    - prod-telegram-bots
    - traefik-system
  kubernetes:
    role: kubesecret-reader
    serviceAccount: default
