apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: wallabag-db
spec:
  instances: 2
  imageName: ghcr.io/cloudnative-pg/postgresql:17.4

  monitoring:
    enablePodMonitor: true

  bootstrap:
    recovery:
      source: backup

  externalClusters:
    - name: backup
      plugin:
        name: barman-cloud.cloudnative-pg.io
        parameters:
          barmanObjectName: google-store

  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: google-store

  storage:
    storageClass: longhorn-single-replica-retain
    size: 5Gi
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: wallabag-db-user
spec:
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  data:
    - secretKey: username
      remoteRef:
        key: wallabag/db-credentials/username
    - secretKey: password
      remoteRef:
        key: wallabag/db-credentials/password
