apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kibana
  labels:
    app: kibana
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
        - name: kibana
          image: docker.elastic.co/kibana/kibana:9.0.4
          env:
            - name: ELASTICSEARCH_HOSTS
              value: '["https://elasticsearch.services.sbling.net:9200"]'
            - name: XPACK_SECURITY_ENABLED
              value: "true"
            - name: ELASTICSEARCH_SERVICEACCOUNTTOKEN
              valueFrom:
                secretKeyRef:
                  name: kibana-credentials
                  key: kibana_sa
            - name: XPACK_SECURITY_ENCRYPTIONKEY
              valueFrom:
                secretKeyRef:
                  name: kibana-credentials
                  key: xpack_security_encryptionKey
            - name: XPACK_REPORTING_ENCRYPTIONKEY
              valueFrom:
                secretKeyRef:
                  name: kibana-credentials
                  key: xpack_reporting_encryptionKey
            - name: XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY
              valueFrom:
                secretKeyRef:
                  name: kibana-credentials
                  key: xpack_encryptedSavedObjects_encryptionKey
            - name: SERVER_PUBLICBASEURL
              value: "https://kibana.services.sbling.net"
          ports:
            - containerPort: 5601
              name: http
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /api/status
              port: 5601
            initialDelaySeconds: 50
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /app/kibana
              port: 5601
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: kibana
spec:
  type: ClusterIP
  selector:
    app: kibana
  ports:
    - port: 5601
      targetPort: 5601
