apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: kibana-credentials
spec:
  destination:
    create: true
    name: kibana-credentials
  mount: kubesecrets
  path: kibana/es-credentials
  type: kv-v2
