apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: keycloak
spec:
  instances: 3
  superuserSecret:
    name: superuser
  bootstrap:
    initdb:
      database: keycloak
      owner: keycloak
      secret:
        name: keycloak-user

  storage:
    size: 5Gi
