apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: keycloak-user
spec:
  destination:
    create: true
    name: keycloak-user
  mount: kubesecrets
  path: keycloak/db-credentials
  type: kv-v2
  vaultAuthRef: prod/vault-auth
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: superuser
spec:
  destination:
    create: true
    name: superuser
  mount: kubesecrets
  path: postgres/superuser
  type: kv-v2
  vaultAuthRef: prod/vault-auth
