apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: airflow

helmCharts:
  - repo: https://airflow.apache.org
    name: airflow
    releaseName: airflow
    version: 1.17.0
    valuesFile: values.yaml
