cluster:
  name: datacenter-k8s

destinations:
  loki:
    type: loki
    url: http://loki-gateway.platform-monitoring-loki.svc.cluster.local/loki/api/v1/push

clusterEvents:
  enabled: true
  collector: alloy-singleton

nodeLogs:
  enabled: true
  collector: alloy-logs

podLogsViaKubernetesApi:
  enabled: true
  collector: alloy-logs

collectors:
  alloy-logs:
    presets:
      - filesystem-log-reader
      - daemonset
    alloy:
      mounts:
        varlog: true
      clustering:
        enabled: true
  alloy-singleton:
    presets:
      - singleton
