apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cert-issuer-prod
spec:
  acme:
    email: luigi.miazzo.93@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: issuer-account-key
    solvers:
      - dns01:
          cloudflare:
            email: luigi.miazzo.93@gmail.com
            apiTokenSecretRef:
              name: cloudflare-api-token-secret
              key: api-token
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: services-sbling-net-prod-cert
spec:
  commonName: "*.services.sbling.net"
  secretName: services-sbling-net-prod-cert
  dnsNames:
    - "*.services.sbling.net"
  issuerRef:
    kind: ClusterIssuer
    name: cert-issuer-prod
