apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cert-issuer-staging
spec:
  acme:
    email: luigi.miazzo.93@gmail.com
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: issuer-account-key
    solvers:
      - dns01:
          cloudflare:
            email: luigi.miazzo.93@gmail.com
            apiTokenSecretRef:
              name: cloudflare-api-token-secret
              key: api-token
