apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: traefik-daashborad-cert
spec:
  commonName: traefik-k8s.services.sbling.net
  secretName: traefik-k8s-services-sbling-net-prod-cert
  dnsNames:
    - traefik-k8s.services.sbling.net
  issuerRef:
    kind: ClusterIssuer
    name: cert-issuer-prod
