apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: oidc-secret
spec:
  destination:
    create: true
    name: oidc-secret
  mount: kubesecrets
  path: traefik-system/oidc-secret
  type: kv-v2
