apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: oidc-secret
spec:
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  data:
    - secretKey: encryptionSecret
      remoteRef:
        key: oidc/traefik/encryption-secret
    - secretKey: clientSecret
      remoteRef:
        key: oidc/traefik/client-secret
