apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: fleet-server-credentials
spec:
  destination:
    create: true
    name: fleet-server-credentials
  mount: kubesecrets
  path: fleet-server/es-credentials
  type: kv-v2
  vaultAuthRef: prod/vault-auth
