apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: es-fleet-server
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  source:
    repoURL: git@github.com:Sbling-Technologies/datacenter-k8s.git
    targetRevision: HEAD
    path: es-fleet-server
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
