apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mariadb
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: mariadb
  source:
    repoURL: git@github.com:Sbling-Technologies/datacenter.git
    targetRevision: HEAD
    path: kube/mariadb
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
