apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: metallb-system
  sources:
    - chart: metallb
      repoURL: https://metallb.github.io/metallb
      targetRevision: 0.14.9
      helm:
        releaseName: metallb
    - repoURL: git@github.com:Sbling-Technologies/datacenter-k8s.git
      targetRevision: HEAD
      path: metallb
  ignoreDifferences:
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      name: bgppeers.metallb.io
      jsonPointers:
        - "/spec/conversion/webhook/clientConfig/caBundle"
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
