apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: portainer
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: portainer
  source:
    repoURL: git@github.com:Sbling-Technologies/datacenter.git
    targetRevision: HEAD
    path: kube/portainer
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
