configuration:
  prometheusUrl: http://kube-prometheus-stack-prometheus.monitoring-system.svc.cluster.local:9090
  alertFilterRegexp: ^(Watchdog|InfoInhibitor|RebootRequired)$
  alertFiringOnly: true

  rebootDays: [wed, thu, sat, sun]
  timeZone: Europe/Rome
  startTime: 2:00
  endTime: 7:00

extraEnvVars:
  - name: KURED_NOTIFY_URL
    valueFrom:
      secretKeyRef:
        name: inchident-bot-secret
        key: url

metrics:
  create: true
