crds:
  enabled: true
podDnsPolicy: None
podDnsConfig:
  nameservers:
    - 1.1.1.1
    - 9.9.9.9
# see: https://github.com/cert-manager/cert-manager/issues/6716
global:
  leaderElection:
    namespace: cert-manager
