apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/name: gatus
  app.kubernetes.io/instance: gatus

# manifests from helm chart: https://github.com/TwiN/helm-charts/tree/master/charts/gatus
resources:
  - database.yaml
  - deployment.yaml
  - ingress.yaml
  - namespace.yaml
  - secrets.yaml
  - service-monitor.yaml
  - service.yaml

configMapGenerator:
  - name: gatus-config
    files:
      - config/config.yaml
      - config/mail.yaml
