apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gatus-env
spec:
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  data:
    - secretKey: HEALTHCHECK_IO_URL
      remoteRef:
        key: gatus/env/healthcheck-io-url

    - secretKey: OIDC_CLIENT_SECRET
      remoteRef:
        key: oidc/gatus-secret

    - secretKey: TELEGRAM_BOT_TOKEN
      remoteRef:
        key: shared/inchident-bot/token
    - secretKey: TELEGRAM_CHAT_ID
      remoteRef:
        key: shared/inchident-bot/chat_id
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gatus-db-user
spec:
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  data:
    - secretKey: username
      remoteRef:
        key: gatus/db-credentials/username
    - secretKey: password
      remoteRef:
        key: gatus/db-credentials/password
