apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: gatus-env
  namespace: gatus
spec:
  destination:
    create: true
    name: gatus
  mount: kubesecrets
  path: gatus/gatus/env
  type: kv-v2
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: gatus-db-user
spec:
  destination:
    create: true
    name: gatus-db-user
  mount: kubesecrets
  path: gatus/db-credentials
  type: kv-v2
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: oidc-secret
spec:
  destination:
    create: true
    name: oidc-secret
  mount: kubesecrets
  path: gatus/oidc-secret
  type: kv-v2
