apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: gatus-env
spec:
  destination:
    create: true
    name: gatus-env
  mount: kubesecrets
  path: gatus/env
  type: kv-v2
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: gatus-db-user
spec:
  destination:
    create: true
    name: gatus-db-user
  mount: kubesecrets
  path: gatus/db-credentials
  type: kv-v2
