apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: gatus-metrics
  labels:
    monitoring: system
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: gatus
  endpoints:
    - port: http
