# -------- #
# Main tab #
# -------- #
- Services:
    - ChangeDetection.io:
        description: Web Site Change Detection, Restock monitoring and notifications
        icon: changedetection
        href: &changedetection_url https://changedetection.services.sbling.net
        siteMonitor: *changedetection_url

    - Mailcow:
        description: Selfhosted mail server
        icon: mailcow
        href: &mailcow_url https://mail.services.sbling.net
        siteMonitor: *mailcow_url

    - Bitwarden:
        description: Password manager
        icon: bitwarden
        href: &bitwarden_url https://bitwarden.services.sbling.net
        siteMonitor: *bitwarden_url

    - n8n:
        description: Easily automate tasks across different services
        icon: n8n
        href: &n8n_url https://n8n.services.sbling.net
        siteMonitor: *n8n_url

- Cluster:
    - Longhorn:
        description: Cloud native distributed block storage for Kubernetes
        icon: longhorn
        href: &longhorn_url https://longhorn.services.sbling.net
        siteMonitor: *longhorn_url

    - Vault:
        description: A tool for secrets management, encryption as a service, and privileged access management
        icon: hashicorp-vault
        href: &vault_url https://vault.services.sbling.net
        siteMonitor: *vault_url

- Monitoring:
    - Grafana Old:
        description: Old instance on docker-main
        icon: grafana
        href: &grafana_url https://grafana-old.services.sbling.net
        siteMonitor: *grafana_url
        widget:
          type: grafana
          url: *grafana_url
          username: "{{HOMEPAGE_VAR_GRAFANA_USER}}"
          password: "{{HOMEPAGE_VAR_GRAFANA_PSWD}}"

    - Prometheus Old:
        description: Old instance on docker-main
        icon: prometheus
        href: &prometheus_url https://prometheus.services.sbling.net
        siteMonitor: *prometheus_url
        widget:
          type: prometheus
          url: *prometheus_url

- Management:
    - Proxmox:
        description: VM manager
        icon: proxmox
        href: &proxmox_url https://proxmox.mgmt.sbling.net:8006
        siteMonitor: *proxmox_url
        widget:
          type: proxmox
          url: *proxmox_url
          username: "{{HOMEPAGE_VAR_PROXMOX_USER}}"
          password: "{{HOMEPAGE_VAR_PROXMOX_PSWD}}"

    - TrueNas:
        description: NAS operating system
        icon: truenas-scale
        href: &truenas_url https://truenas.services.sbling.net
        siteMonitor: *truenas_url
        widget:
          type: truenas
          url: *truenas_url
          key: "{{HOMEPAGE_VAR_TRUENAS_KEY}}"

    - ILO4 st-srv-001:
        description: Integrated Lights Out
        icon: ilo
        href: https://st-srv-001.mgmt.sbling.net

    - UDM:
        description: Ubiquiti Dream Machine
        icon: ubiquiti
        href: https://sblenghito.mgmt.sbling.net/network
        siteMonitor: &udm_url https://sblenghito.mgmt.sbling.net
        widget:
          type: unifi
          url: *udm_url
          username: "{{HOMEPAGE_VAR_UNIFI_USER}}"
          password: "{{HOMEPAGE_VAR_UNIFI_PSWD}}"

    - PowerDNS:
        description: Authoritative DNS server
        icon: powerdns
        href: &pdns_url http://ddi.services.sbling.net:8989
        siteMonitor: *pdns_url

# --------- #
# Media tab #
# --------- #
- Plex Stack:
    - Plex:
        description: Plex streaming media service.
        icon: plex
        href: &plex_url https://plex.media.sbling.net
        siteMonitor: *plex_url

    - Overseerr:
        description: Request management and media discovery tool for the Plex ecosystem.
        icon: overseerr
        href: &overseerr_url https://overseerr.media.sbling.net
        siteMonitor: *overseerr_url

- Jellyfin Stack:
    - Jellyfin:
        description: The Free Software Media System.
        icon: jellyfin
        href: &jellyfin_url https://jellyfin.media.sbling.net
        siteMonitor: *jellyfin_url

    - Jellyseerr:
        description: Fork of Overseerr for Jellyfin support.
        icon: jellyseerr
        href: &jellyseerr_url https://jellyseerr.media.sbling.net
        siteMonitor: *jellyseerr_url

- Media Management:
    - Prowlarr:
        description: An indexer manager/proxy built to integrate with your various PVR apps.
        icon: prowlarr
        href: &prowlarr_url https://prowlarr.media.sbling.net
        siteMonitor: *prowlarr_url

    - Radarr:
        description: Movie organizer/manager for usenet and torrent users.
        icon: radarr
        href: &radarr_url https://radarr.media.sbling.net
        siteMonitor: *radarr_url

    - Sonarr:
        description: Smart PVR for newsgroup and BitTorrent users.
        icon: sonarr
        href: &sonarr_url https://sonarr.media.sbling.net
        siteMonitor: *sonarr_url

    - Bazarr:
        description: A companion application to Sonarr and Radarr. It manages and downloads subtitles based on your requirements.
        icon: bazarr
        href: &bazarr_url https://bazarr.media.sbling.net
        siteMonitor: *bazarr_url

    - qBittorrent:
        description: A cross-platform free and open-source BitTorrent client written in native C++.
        icon: qbittorrent
        href: &qbittorrent_url https://qbittorrent.media.sbling.net
        siteMonitor: *qbittorrent_url
