cluster:
  name: sbling-prod

rollOutCiliumPods: true
kubeProxyReplacement: true
k8sServiceHost: kube.services.sbling.net
k8sServicePort: 6443
bpf:
  masquerade: true

l2announcements:
  enabled: true
k8sClientRateLimit:
  # https://docs.cilium.io/en/latest/network/l2-announcements/#sizing-client-rate-limit
  qps: 30
  burst: 40

ipam:
  operator:
    clusterPoolIPv4PodCIDRList:
      - 10.44.0.0/16

ingressController:
  enabled: true
  default: true
  defaultSecretNamespace: cert-manager
  defaultSecretName: services-sbling-net-prod-cert
gatewayAPI:
  enabled: true
loadBalancer:
  l7:
    backend: envoy

hubble:
  relay:
    enabled: true
  ui:
    enabled: true

  metrics:
    enableOpenMetrics: true
    enabled:
      - dns
      - drop
      - tcp
      - flow
      - port-distribution
      - icmp
      - http
    serviceMonitor:
      enabled: true

prometheus:
  enabled: true
  serviceMonitor:
    enabled: true
    trustCRDsExist: true

operator:
  prometheus:
    enabled: true
    serviceMonitor:
      enabled: true
