cluster:
  name: sbling-prod

kubeProxyReplacement: true
k8sServiceHost: kube.services.sbling.net
k8sServicePort: 6443

ipam:
  operator:
    clusterPoolIPv4PodCIDRList:
      - 10.44.0.0/16

hubble:
  relay:
    enabled: true
  ui:
    enabled: true

  metrics:
    enabled:
      - dns
      - drop
      - tcp
      - flow
      - port-distribution
      - icmp
      - httpV2:exemplars=true;labelsContext=source_ip,source_namespace,source_workload,destination_ip,destination_namespace,destination_workload,traffic_direction
    serviceMonitor:
      enabled: true

prometheus:
  enabled: true
  serviceMonitor:
    enabled: true

operator:
  prometheus:
    enabled: true
    serviceMonitor:
      enabled: true
