cluster:
  name: sbling-prod

rollOutCiliumPods: true
kubeProxyReplacement: true
k8sServiceHost: kube.services.sbling.net
k8sServicePort: 6443
bpf:
  masquerade: true

ipam:
  operator:
    clusterPoolIPv4PodCIDRList:
      - 10.44.0.0/16

gatewayAPI:
  enabled: true
loadBalancer:
  l7:
    backend: envoy

hubble:
  relay:
    enabled: true
  ui:
    enabled: true

  metrics:
    enableOpenMetrics: true
    enabled:
      - dns
      - drop
      - tcp
      - flow
      - port-distribution
      - icmp
      - http
    serviceMonitor:
      enabled: true

prometheus:
  enabled: true
  serviceMonitor:
    enabled: true
    trustCRDsExist: true

operator:
  prometheus:
    enabled: true
    serviceMonitor:
      enabled: true
