cluster:
  name: sbling-prod

bpf:
  hostLegacyRouting: false

tunnelPort: 8473
ipam:
  operator:
    clusterPoolIPv4PodCIDRList:
      - 10.44.0.0/16

hubble:
  relay:
    enabled: true
  ui:
    enabled: true
