expose:
  ingress:
    hosts:
      core: harbor.services.sbling.net
    annotations:
      gethomepage.dev/enabled: "true"
      gethomepage.dev/name: Harbor
      gethomepage.dev/description: An open source trusted cloud native registry project that stores, signs, and scans content.
      gethomepage.dev/group: Services
      gethomepage.dev/icon: harbor
      gethomepage.dev/pod-selector: ""
  tls:
    certSource: secret
    secret:
      secretName: harbor-services-sbling-net-prod-cert

externalURL: https://harbor.services.sbling.net

database:
  type: external
  external:
    host: harbor-db-rw.prod-harbor.svc.cluster.local
    coreDatabase: harbor
    username: harbor
    existingSecret: db-credentials

persistence:
  persistentVolumeClaim:
    registry:
      accessMode: ReadWriteMany
    jobservice:
      jobLog:
        accessMode: ReadWriteMany
