apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apps-prod
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: git@github.com:Sbling-Technologies/datacenter-k8s.git
        revision: HEAD
        directories:
          - path: applications/*

  template:
    metadata:
      name: "prod-{{.path.basenameNormalized}}"
    spec:
      project: default
      destination:
        server: https://kubernetes.default.svc
        namespace: "prod-{{.path.basenameNormalized}}"
      source:
        repoURL: git@github.com:Sbling-Technologies/datacenter-k8s.git
        targetRevision: HEAD
        path: "{{.path.path}}"
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
