apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apps-staging
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: git@github.com:Sbling-Technologies/datacenter-k8s.git
        revision: HEAD
        directories:
          - path: applications/**/overlays/staging

  template:
    metadata:
      name: "{{index .path.segments 3}}-{{index .path.segments 1}}"
    spec:
      project: default
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{index .path.segments 3}}-{{index .path.segments 1}}"
      sourceHydrator:
        drySource:
          repoURL: git@github.com:Sbling-Technologies/datacenter-k8s.git
          targetRevision: HEAD
          path: "{{.path.path}}"
          kustomize:
            namespace: "{{index .path.segments 3}}-{{index .path.segments 1}}"
        syncSource:
          targetBranch: environments/staging
          path: "{{index .path.segments 0}}/{{index .path.segments 1}}"
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
