apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dex-secrets
spec:
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  data:
    - secretKey: GITHUB_CLIENT_ID
      remoteRef:
        key: oidc/connectors/github/client-id
    - secretKey: GITHUB_CLIENT_SECRET
      remoteRef:
        key: oidc/connectors/github/client-secret
