apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: argocd
  namespace: argocd
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`argocd.services.sbling.net`)
      kind: Rule
      services:
        - name: argocd-server
          port: 443
          serversTransport: no-verify-tls
  tls:
    secretName: argocd-services-sbling-net-prod-cert
---
apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: no-verify-tls
  namespace: argocd
spec:
  insecureSkipVerify: true
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-cert
  namespace: argocd
spec:
  commonName: argocd.services.sbling.net
  secretName: argocd-services-sbling-net-prod-cert
  dnsNames:
    - argocd.services.sbling.net
  issuerRef:
    kind: ClusterIssuer
    name: cert-issuer-prod
