apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd
  annotations:
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: ArgoCD
    gethomepage.dev/description: Declarative GitOps CD for Kubernetes
    gethomepage.dev/group: Cluster
    gethomepage.dev/icon: argo-cd
    gethomepage.dev/pod-selector: ""
spec:
  ingressClassName: traefik
  rules:
    - host: argocd.services.sbling.net
      http:
        paths:
          - backend:
              service:
                name: argocd-server
                port:
                  number: 443
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - argocd.services.sbling.net
      secretName: argocd-services-sbling-net-prod-cert
---
apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: no-verify-tls
spec:
  insecureSkipVerify: true
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-cert
spec:
  commonName: argocd.services.sbling.net
  secretName: argocd-services-sbling-net-prod-cert
  dnsNames:
    - argocd.services.sbling.net
  issuerRef:
    kind: ClusterIssuer
    name: cert-issuer-prod
