apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: repo-datacenter-k8s-push
  labels:
    argocd.argoproj.io/secret-type: repository-write
spec:
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    template:
      data:
        type: git
        url: "{{ .url }}"
        sshPrivateKey: "{{ .sshPrivateKey }}"
  data:
    - secretKey: url
      remoteRef:
        key: argocd/repo/datacenter-k8s/push/url
    - secretKey: sshPrivateKey
      remoteRef:
        key: argocd/repo/datacenter-k8s/push/ssh-private-key
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-oidc-secret
  labels:
    app.kubernetes.io/part-of: argocd
spec:
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  data:
    - secretKey: dex.oidc.clientSecret
      remoteRef:
        key: oidc/argocd/client-secret
