name: Build OCI Images

on:
  pull_request:
    paths: &paths
      - .github/workflows/build-images.yaml
      - "images/**"
  push:
    paths: *paths
    branches:
      - master

jobs:
  detect-images:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.names.outputs.matrix }}
      any_changed: ${{ steps.changed.outputs.any_changed }}
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
        with:
          fetch-depth: 0

      - name: Detect changed images
        id: changed
        uses: tj-actions/changed-files@24d32ffd492484c1d75e0c0b894501ddb9d30d62 # v47
        with:
          files: "images/**"
          dir_names: "true"
          dir_names_max_depth: "2"
          matrix: "true"

      - name: Reduce to image names
        id: names
        run: |
          matrix=$(echo '${{ steps.changed.outputs.all_changed_files }}' | jq -c '[.[] | sub("^images/"; "")]')
          echo "matrix=$matrix" >> "$GITHUB_OUTPUT"

  build:
    needs: detect-images
    if: needs.detect-images.outputs.any_changed == 'true'
    strategy:
      matrix:
        name: ${{ fromJson(needs.detect-images.outputs.matrix) }}
      fail-fast: false
    permissions:
      contents: read
      packages: write
    uses: ardubev16/common/.github/workflows/docker-build.yaml@main
    with:
      image-name: ${{ github.event.repository.name }}/${{ matrix.name }}
      context: images/${{ matrix.name }}
      tags: |
        type=raw,value=latest,enable={{is_default_branch}}
        type=raw,value={{date 'YYYYMMDDTHHmmss'}},enable={{is_default_branch}}
        type=raw,value=pr-${{ github.event.pull_request.number }},enable=${{ github.event_name == 'pull_request' }}
