name: Cleanup PR Images

on:
  workflow_dispatch:
  pull_request:
    types:
      - closed
    paths:
      - .github/workflows/cleanup-pr-images.yaml
      - "images/**"

jobs:
  detect-images:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.list.outputs.matrix }}
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

      - name: List images
        id: list
        run: |
          matrix=$(find images -mindepth 1 -maxdepth 1 -type d -printf '%f\n' | jq -R . | jq -cs .)
          echo "matrix=$matrix" >> "$GITHUB_OUTPUT"

  cleanup:
    needs: detect-images
    strategy:
      matrix:
        name: ${{ fromJson(needs.detect-images.outputs.matrix) }}
      fail-fast: false
    permissions:
      packages: write
    uses: ardubev16/common/.github/workflows/docker-clean-pr.yaml@main
    with:
      image-name: ${{ github.event.repository.name }}/${{ matrix.name }}
      pr-number: ${{ github.event.pull_request.number }}
