name: Show applications diff

on:
  pull_request:

jobs:
  detect-apps:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.applications.outputs.all_changed_files }}
      any_changed: ${{ steps.applications.outputs.any_changed }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - uses: tj-actions/changed-files@24d32ffd492484c1d75e0c0b894501ddb9d30d62 # v47
        id: applications
        with:
          files: applications/**
          dir_names_max_depth: "2"
          # files: applications/*/envs/prod/**
          # dir_names_max_depth: "4"
          dir_names: "true"
          matrix: "true"

  comment-diff:
    needs: detect-apps
    if: needs.detect-apps.outputs.any_changed == 'true'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        directory: ${{ fromJson(needs.detect-apps.outputs.matrix) }}
      fail-fast: false
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 0

      - name: Calculate diff
        id: diff
        env:
          DIRECTORY: ${{ matrix.directory }}
        run: |
          kustomize build --enable-helm "$DIRECTORY" > /tmp/pr_run.yaml
          git checkout origin/master -- "$DIRECTORY"
          kustomize build --enable-helm "$DIRECTORY" > /tmp/pr_base.yaml

          diff=$(diff -C 5 /tmp/pr_base.yaml /tmp/pr_run.yaml || true)
          {
            echo "diff<<EOF"
            echo "$diff"
            echo "EOF"
          } >> "$GITHUB_OUTPUT"

      - name: Find Comment
        uses: peter-evans/find-comment@v3
        id: fc
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: "github-actions[bot]"
          body-includes: Application diff for `${{ matrix.directory }}`

      - name: Create or update comment
        uses: peter-evans/create-or-update-comment@v5
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            Application diff for `${{ matrix.directory }}`
            ```diff
            ${{ steps.diff.outputs.diff }}
            ```
          edit-mode: replace
