storage:
  type: postgres
  path: postgres://${POSTGRES_USERNAME}:${POSTGRES_PASSWORD}@gatus-db-rw:5432/gatus

security:
  oidc:
    issuer-url: https://keycloak.services.sbling.net/realms/sbling
    redirect-url: https://gatus.services.sbling.net/authorization-code/callback
    client-id: gatus
    client-secret: ${OIDC_CLIENT_SECRET}
    scopes: [openid]

alerting:
  telegram:
    token: ${TELEGRAM_BOT_TOKEN}
    id: ${TELEGRAM_CHAT_ID}
    default-alert:
      send-on-resolved: true
      failure-threshold: 2
      success-threshold: 2

x-https-common: &https-common
  conditions:
    - "[STATUS] == 200"
    - "[CERTIFICATE_EXPIRATION] > 168h" # 7d
  alerts:
    - type: telegram

endpoints:
  - name: Healthcheck.io
    method: POST
    interval: 1m
    conditions:
      - "[STATUS] == 200"
      - "[BODY] == OK"
    alerts:
      - type: telegram
    url: ${HEALTHCHECK_IO_URL}

  - name: UDM
    conditions:
      - " [CONNECTED] == true"
    alerts:
      - type: telegram
    url: icmp://gateway.services.sbling.net

  - name: TrueNAS
    <<: *https-common
    url: https://truenas.services.sbling.net/

  - name: Traefik
    <<: *https-common
    url: https://traefik.services.sbling.net/

  - name: Bitwarden
    <<: *https-common
    url: https://bitwarden.services.sbling.net/

  - name: Homepage
    <<: *https-common
    url: https://homepage.services.sbling.net/

  - name: Kibana
    <<: *https-common
    url: https://kibana.services.sbling.net/

  - name: Keycloak
    <<: *https-common
    url: https://keycloak.services.sbling.net/

  - name: Harbor
    <<: *https-common
    url: https://harbor.services.sbling.net/
