apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod-elasticsearch

resources:
  - base/ingress.yaml
  - base/namespace.yaml
  - base/services.yaml

secretGenerator:
  - name: es-root-ca
    options:
      disableNameSuffixHash: true
    files:
      - ca.crt
