apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod-elasticsearch

resources:
  - base/configmap.yaml
  - base/deployment.yaml
  - base/ingress.yaml
  - base/namespace.yaml
  - base/secret.yaml
  - base/service.yaml
