apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: longhorn-system

helmCharts:
  - repo: https://charts.longhorn.io
    name: longhorn
    releaseName: longhorn
    version: 1.9.1
    valuesFile: values.yaml
    namespace: longhorn-system

resources:
  - base/monitoring
  - base/ingress.yaml
  - base/middleware-oidc-auth.yaml
  - base/secrets.yaml
  - base/storage-classes.yaml
